### ISSUE TITLE
GRU output

### ISSUE THREAD

**Issue by eagomez2** [piotrkawa/specrnet#1]
Hi,

Following the code I notice that part of the GRU output is dropped: https://github.com/piotrkawa/specrnet/blob/main/model.py#L155

What is the reason behind it?

Thanks,
Esteban

**Comment by piotrkawa** [comment]
Hi!
The SpecRNet architecture is based on RawNet2. As in the original - this line extracts information from the last step of the GRU network for each sample in a batch.

Best regards,
Piotr

**Comment by eagomez2** [comment]
Thanks! It clarifies my question.
